# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: archivo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rarchivo.proto\x12\x07\x61rchivo\x1a\x1bgoogle/protobuf/empty.proto\" \n\x0c\x41rchivoLista\x12\x10\n\x08\x61rchivos\x18\x01 \x03(\t2\x8b\x01\n\x07\x41rchivo\x12?\n\x0eListarArchivos\x12\x16.google.protobuf.Empty\x1a\x15.archivo.ArchivoLista\x12?\n\x0e\x42uscarArchivos\x12\x16.google.protobuf.Empty\x1a\x15.archivo.ArchivoListab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'archivo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ARCHIVOLISTA']._serialized_start=55
  _globals['_ARCHIVOLISTA']._serialized_end=87
  _globals['_ARCHIVO']._serialized_start=90
  _globals['_ARCHIVO']._serialized_end=229
# @@protoc_insertion_point(module_scope)
